---
# handlers file for nginx-docker

- name: start service docker
  service:
    name: docker
    state: started
    enabled: yes


- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded
