---
# install docker and component on Ubuntu Test server

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install dependency packages
  apt:
    name: "{{ item }}"
    loop:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Install Docker ce and other components
  apt:
    name: "{{ item }}" 
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    notify: start docker
